### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 2. Received 4

### ISSUE THREAD

**Issue by sfodor** [CollinearGroup/pcap-ng-parser#1]
In the readOptions(..) of file \pcap-ng-parser\src\PCAPNGParser.js, do we need the "=" in the "while (pos <= buf.length || foundEndOption) {" line?

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 2. Received 4
    at boundsError (internal/buffer.js:82:9)
    at Buffer.readUInt16LE (internal/buffer.js:239:5)
    at PCAPNGParser.readBlock (...\node_modules\pcap-ng-parser\src\PCAPNGParser.js:86:42)
    at PCAPNGParser.readOptions (...\node_modules\pcap-ng-parser\src\PCAPNGParser.js:136:27)
    at PCAPNGParser.processRawBlock (...\node_modules\pcap-ng-parser\src\PCAPNGParser.js:164:33)
    at PCAPNGParser._transform (...\node_modules\pcap-ng-parser\src\PCAPNGParser.js:49:48)
    at PCAPNGParser.Transform._read (_stream_transform.js:191:10)
    at PCAPNGParser.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5) {
  code: 'ERR_OUT_OF_RANGE'

**Comment by TheGigaQuant** [comment]
Not needed.
Work without error if you delete it

**Comment by hildjj** [comment]
Fixed in https://github.com/cto-af/pcap-ng-parser
